# Generated by Django 5.2.5 on 2026-04-07 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "groups",
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("dni", models.CharField(max_length=20, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "parents",
                "indexes": [
                    models.Index(fields=["dni"], name="parents_dni_947d62_idx"),
                    models.Index(fields=["email"], name="parents_email_346afe_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("is_adult", models.BooleanField(default=False, verbose_name="Estudiante adulto (18+)")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email (solo adultos)")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Teléfono (solo adultos)")),
                ("school", models.CharField(blank=True, max_length=200)),
                ("allergies", models.TextField(blank=True)),
                ("gdpr_signed", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("withdrawal_date", models.DateField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="students", to="students.group"
                    ),
                ),
            ],
            options={
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("parent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="students.parent")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="students.student")),
            ],
            options={
                "db_table": "student_parents",
                "unique_together": {("student", "parent")},
            },
        ),
        migrations.AddField(
            model_name="student",
            name="parents",
            field=models.ManyToManyField(
                related_name="children", through="students.StudentParent", to="students.parent"
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teachers",
                "indexes": [
                    models.Index(fields=["email"], name="teachers_email_87e41d_idx"),
                    models.Index(fields=["active"], name="teachers_active_84777b_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="groups", to="students.teacher"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["group"], name="students_group_i_234511_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["active"], name="students_active_005329_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["birth_date"], name="students_birth_d_3e1fc4_idx"),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["group_name"], name="groups_group_n_2d53de_idx"),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["teacher"], name="groups_teacher_f856b2_idx"),
        ),
    ]
