# Generated by Django 5.2.5 on 2025-12-28 18:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('adults', 'Adults'), ('special', 'Special'), ('languages_ticket', 'Languages Ticket'), ('monthly', 'Monthly'), ('half_month', 'Half-month'), ('quarterly', 'Quarterly')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('base_amount_full_time', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('base_amount_part_time', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enrollment_types',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parents',
                'indexes': [models.Index(fields=['dni'], name='parents_dni_947d62_idx'), models.Index(fields=['email'], name='parents_email_346afe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('school', models.CharField(blank=True, max_length=200)),
                ('allergies', models.TextField(blank=True)),
                ('gdpr_signed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.group')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_period_start', models.DateField()),
                ('enrollment_period_end', models.DateField()),
                ('schedule_type', models.CharField(choices=[('full_time', 'Full-time (2 classes/week)'), ('part_time', 'Part-time (1 class/week)'), ('adult_group', 'Adult group (1 class/week)')], default='full_time', max_length=20)),
                ('enrollment_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending', max_length=10)),
                ('enrollment_date', models.DateField()),
                ('document_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.enrollmenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.student')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'db_table': 'student_parents',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='core.StudentParent', to='core.parent'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teachers',
                'indexes': [models.Index(fields=['email'], name='teachers_email_87e41d_idx'), models.Index(fields=['active'], name='teachers_active_84777b_idx')],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='core.teacher'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('enrollment', 'Enrollment Fee'), ('monthly', 'Monthly Fee'), ('quarterly', 'Quarterly Fee'), ('other', 'Other')], default='monthly', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('credit_card', 'Credit Card')], default='transfer', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('concept', models.CharField(max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('observations', models.TextField(blank=True)),
                ('document_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.enrollment')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.student')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['student'], name='payments_student_5b85b3_idx'), models.Index(fields=['parent'], name='payments_parent__d631d3_idx'), models.Index(fields=['payment_status'], name='payments_payment_bbdde9_idx'), models.Index(fields=['due_date'], name='payments_due_dat_ff319d_idx'), models.Index(fields=['payment_date'], name='payments_payment_aebcb7_idx'), models.Index(fields=['enrollment'], name='payments_enrollm_7d7109_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='enrollments_student_379f04_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='enrollments_status_dfab18_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_date'], name='enrollments_enrollm_4c2d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_period_start'], name='enrollments_enrollm_fa02e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student',), name='unique_active_enrollment_per_student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentparent',
            unique_together={('student', 'parent')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['group'], name='students_group_i_234511_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['active'], name='students_active_005329_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['birth_date'], name='students_birth_d_3e1fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_name'], name='groups_group_n_2d53de_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher'], name='groups_teacher_f856b2_idx'),
        ),
    ]
