# Generated by Django 5.2.5 on 2025-09-14 07:52

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('adults', 'Adults'), ('special', 'Special'), ('languages_ticket', 'Languages Ticket'), ('monthly', 'Monthly'), ('half_month', 'Half-month'), ('quarterly', 'Quarterly')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('base_amount_full_time', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('base_amount_part_time', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enrollment_types',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('operational', 'Operational'), ('administrative', 'Administrative'), ('marketing', 'Marketing'), ('infrastructure', 'Infrastructure'), ('legal', 'Legal & Compliance'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_tax_deductible', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'expense_categories',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_closed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'financial_periods',
                'unique_together': {('period_type', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parents',
                'indexes': [models.Index(fields=['dni'], name='parents_dni_947d62_idx'), models.Index(fields=['email'], name='parents_email_346afe_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpenseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_tax_id', models.CharField(blank=True, max_length=50)),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_generate', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_templates', to='core.expensecategory')),
            ],
            options={
                'db_table': 'recurring_expense_templates',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('allergies', models.TextField(blank=True)),
                ('gdpr_signed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.group')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_period_start', models.DateField()),
                ('enrollment_period_end', models.DateField()),
                ('schedule_type', models.CharField(choices=[('full_time', 'Full-time (2 classes/week)'), ('part_time', 'Part-time (1 class/week)')], default='full_time', max_length=10)),
                ('enrollment_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending', max_length=10)),
                ('enrollment_date', models.DateField()),
                ('document_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.enrollmenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.student')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'db_table': 'student_parents',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='core.StudentParent', to='core.parent'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teachers',
                'indexes': [models.Index(fields=['email'], name='teachers_email_87e41d_idx'), models.Index(fields=['active'], name='teachers_active_84777b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_type', models.CharField(choices=[('monthly_salary', 'Monthly Salary'), ('hourly_payment', 'Hourly Payment'), ('bonus', 'Bonus'), ('commission', 'Commission'), ('reimbursement', 'Reimbursement'), ('other', 'Other')], default='monthly_salary', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tax_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='core.teacher')),
            ],
            options={
                'db_table': 'payrolls',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='core.teacher'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_tax_id', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('expense_type', models.CharField(choices=[('recurring', 'Recurring'), ('one_time', 'One-time'), ('reimbursement', 'Reimbursement')], default='one_time', max_length=15)),
                ('expense_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('check', 'Check'), ('direct_debit', 'Direct Debit')], max_length=15)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('receipt_url', models.URLField(blank=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.expensecategory')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to='core.teacher')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('enrollment', 'Enrollment Fee'), ('monthly', 'Monthly Fee'), ('materials', 'Materials'), ('registration', 'Registration'), ('exam', 'Exam Fee'), ('other', 'Other')], default='monthly', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'In Cash'), ('transfer', 'Transference'), ('credit_card', 'Credit Card')], default='transfer', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='Set to False to hide payment from main views (soft delete)')),
                ('concept', models.CharField(max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('observations', models.TextField(blank=True)),
                ('document_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.enrollment')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.student')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['student'], name='payments_student_5b85b3_idx'), models.Index(fields=['parent'], name='payments_parent__d631d3_idx'), models.Index(fields=['payment_status'], name='payments_payment_bbdde9_idx'), models.Index(fields=['due_date'], name='payments_due_dat_ff319d_idx'), models.Index(fields=['payment_date'], name='payments_payment_aebcb7_idx'), models.Index(fields=['enrollment'], name='payments_enrollm_7d7109_idx'), models.Index(fields=['active'], name='payments_active_43444c_idx')],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='enrollments_student_379f04_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='enrollments_status_dfab18_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_date'], name='enrollments_enrollm_4c2d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_period_start'], name='enrollments_enrollm_fa02e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student',), name='unique_active_enrollment_per_student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentparent',
            unique_together={('student', 'parent')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['group'], name='students_group_i_234511_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['active'], name='students_active_005329_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['birth_date'], name='students_birth_d_3e1fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['teacher'], name='payrolls_teacher_609a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='payrolls_status_366245_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['payment_date'], name='payrolls_payment_4cb0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['period_start'], name='payrolls_period__79b245_idx'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('teacher', 'period_start', 'period_end', 'payroll_type'), name='unique_payroll_per_teacher_period'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_name'], name='groups_group_n_2d53de_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher'], name='groups_teacher_f856b2_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='expenses_expense_43600a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='expenses_status_86293f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expenses_categor_80dcb8_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['vendor_name'], name='expenses_vendor__24fd71_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['due_date'], name='expenses_due_dat_2bb169_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_number'], name='expenses_expense_003f04_idx'),
        ),
    ]
