# Generated by Django 5.2.5 on 2025-12-29 08:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_enrollment_fee', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Matrícula niños')),
                ('adult_enrollment_fee', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Matrícula adultos')),
                ('full_time_monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('54.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Mensualidad jornada completa')),
                ('part_time_monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('36.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Mensualidad media jornada')),
                ('adult_group_monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Mensualidad grupo adultos')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
                'db_table': 'site_configuration',
            },
        ),
    ]
