# Generated by Django 5.2.5 on 2026-03-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_todo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
    ]
