# Generated by Django 5.2.5 on 2026-03-13 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_color_to_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('day', models.IntegerField()),
                ('col', models.IntegerField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='core.group')),
            ],
            options={
                'ordering': ['row', 'day', 'col'],
                'unique_together': {('row', 'day', 'col')},
            },
        ),
    ]
