# Generated by Django 5.2.5 on 2026-03-13 14:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_fun_friday_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='full_year_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Año completo (€ fijo, no adultos)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='half_month_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Medio mes — septiembre (%)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='language_cheque_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cheque idioma (€ fijo)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='old_student_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Alumno antiguo (€ fijo)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='one_week_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Solo 1 semana — primer mes (%)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='quarterly_enrollment_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Matrícula trimestral (%)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='sibling_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Hermanos (% mensual)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='three_week_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Solo 3 semanas (%)'),
        ),
    ]
