# Generated by Django 5.2.5 on 2026-03-22 09:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_discount_fields_to_site_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='has_language_cheque',
            field=models.BooleanField(default=False, verbose_name='Cheque idioma'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_sibling_discount',
            field=models.BooleanField(default=False, verbose_name='Descuento hermano'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_modality',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral')], default='monthly', max_length=10, verbose_name='Modalidad de pago'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='june_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento junio — completar año (€ fijo)'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (solo adultos)'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='Estudiante adulto (18+)'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono (solo adultos)'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='schedule_type',
            field=models.CharField(choices=[('full_time', '2 días/semana'), ('part_time', '1 día/semana'), ('adult_group', 'Adultos (1 día/semana)')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.parent'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='old_student_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Alumno antiguo (€ fijo)'),
        ),
    ]
