# Generated by Django 5.2.5 on 2026-03-24 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enrollment_payment_system_rework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('credit_card', 'Tarjeta')], default='transfer', max_length=15),
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('todo_completed', 'Tarea completada'), ('payment_completed', 'Pago completado'), ('student_enrolled', 'Alumno matriculado'), ('teacher_created', 'Profesor creado'), ('group_created', 'Grupo creado'), ('group_updated', 'Grupo actualizado'), ('config_updated', 'Configuración actualizada'), ('payment_created', 'Pago creado'), ('email_sent', 'Email enviado')], max_length=30)),
                ('message', models.CharField(max_length=300)),
                ('icon', models.CharField(default='history', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'history_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='history_log_created_bc72c4_idx')],
            },
        ),
    ]
