# Generated by Django 5.2.5 on 2026-03-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_payment_payment_method_historylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylog',
            name='action',
            field=models.CharField(choices=[('todo_completed', 'Tarea completada'), ('payment_completed', 'Pago completado'), ('student_enrolled', 'Alumno matriculado'), ('teacher_created', 'Profesor creado'), ('group_created', 'Grupo creado'), ('group_updated', 'Grupo actualizado'), ('config_updated', 'Configuración actualizada'), ('payment_created', 'Pago creado'), ('email_sent', 'Email enviado'), ('schedule_updated', 'Horario actualizado')], max_length=30),
        ),
    ]
