# Generated by Django 5.2.5 on 2026-04-07 20:06

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import billing.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("adults", "Adults"),
                            ("special", "Special"),
                            ("languages_ticket", "Languages Ticket"),
                            ("monthly", "Monthly"),
                            ("half_month", "Half-month"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=50)),
                (
                    "base_amount_full_time",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "base_amount_part_time",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "enrollment_types",
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "children_enrollment_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("40.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Matrícula niños",
                    ),
                ),
                (
                    "adult_enrollment_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Matrícula adultos",
                    ),
                ),
                (
                    "full_time_monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("54.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Mensualidad jornada completa",
                    ),
                ),
                (
                    "part_time_monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("36.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Mensualidad media jornada",
                    ),
                ),
                (
                    "adult_group_monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("60.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Mensualidad grupo adultos",
                    ),
                ),
                (
                    "language_cheque_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Cheque idioma (€ fijo)",
                    ),
                ),
                (
                    "quarterly_enrollment_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Matrícula trimestral (%)",
                    ),
                ),
                (
                    "old_student_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Alumno antiguo (€ fijo)",
                    ),
                ),
                (
                    "june_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Descuento junio — completar año (€ fijo)",
                    ),
                ),
                (
                    "full_year_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Año completo (€ fijo, no adultos)",
                    ),
                ),
                (
                    "sibling_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Hermanos (% mensual)",
                    ),
                ),
                (
                    "half_month_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Medio mes — septiembre (%)",
                    ),
                ),
                (
                    "one_week_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("75.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Solo 1 semana — primer mes (%)",
                    ),
                ),
                (
                    "three_week_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Solo 3 semanas (%)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración del sitio",
                "verbose_name_plural": "Configuración del sitio",
                "db_table": "site_configuration",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enrollment_period_start", models.DateField()),
                ("enrollment_period_end", models.DateField()),
                ("academic_year", models.CharField(default=billing.models.current_academic_year, max_length=9)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("full_time", "2 días/semana"),
                            ("part_time", "1 día/semana"),
                            ("adult_group", "Adultos (1 día/semana)"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "payment_modality",
                    models.CharField(
                        choices=[("monthly", "Mensual"), ("quarterly", "Trimestral")],
                        default="monthly",
                        max_length=10,
                        verbose_name="Modalidad de pago",
                    ),
                ),
                ("has_language_cheque", models.BooleanField(default=False, verbose_name="Cheque idioma")),
                ("is_sibling_discount", models.BooleanField(default=False, verbose_name="Descuento hermano")),
                (
                    "enrollment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("enrollment_date", models.DateField()),
                ("document_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="enrollments", to="students.student"
                    ),
                ),
                (
                    "enrollment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="billing.enrollmenttype",
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("enrollment", "Enrollment Fee"),
                            ("monthly", "Monthly Fee"),
                            ("quarterly", "Quarterly Fee"),
                            ("other", "Other"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Efectivo"), ("transfer", "Transferencia"), ("credit_card", "Tarjeta")],
                        default="transfer",
                        max_length=15,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("concept", models.CharField(max_length=200)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("observations", models.TextField(blank=True)),
                ("document_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.enrollment",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="students.parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="students.student"
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["student"], name="enrollments_student_379f04_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["status"], name="enrollments_status_dfab18_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["enrollment_date"], name="enrollments_enrollm_4c2d2b_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["enrollment_period_start"], name="enrollments_enrollm_fa02e0_idx"),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("student",),
                name="unique_active_enrollment_per_student",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["student"], name="payments_student_5b85b3_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["parent"], name="payments_parent__d631d3_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_status"], name="payments_payment_bbdde9_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["due_date"], name="payments_due_dat_ff319d_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_date"], name="payments_payment_aebcb7_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["enrollment"], name="payments_enrollm_7d7109_idx"),
        ),
    ]
